version: '3.8'

services:
  # Next.js application
  web:
    build:
      context: .
      target: runner
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

  # Nginx reverse proxy with HTTPS
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - app-network

  # Optional: Redis for caching (uncomment if needed)
  # redis:
  #   image: redis:alpine
  #   restart: unless-stopped
  #   networks:
  #     - app-network
  #   volumes:
  #     - redis-data:/data

networks:
  app-network:
    driver: bridge

# volumes:
#   redis-data: 