version: '3.8'

services:
  # Production Next.js App
  web:
    build:
      context: .
      target: runner
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - app-network

  # Optional: Redis for caching (uncomment if needed)
  # redis:
  #   image: redis:alpine
  #   restart: unless-stopped
  #   networks:
  #     - app-network
  #   volumes:
  #     - redis-data:/data

networks:
  app-network:
    driver: bridge

# volumes:
#   redis-data: 